export const ACTION_TYPES = {
  UPDATE_WORD: 'UPDATE_WORD',
  UPDATE_WORD_RESOURCE: 'UPDATE_WORD_RESOURCE',
  DELETE_WORD_RESOURCE: 'DELETE_WORD_RESOURCE',
  CREATE_WORD_RESOURCE: 'CREATE_WORD_RESOURCE',
  SET_WORDS: 'SET_WORDS',
} as const;
