export const ACTION_TYPES = {
  REVERT_CARD: 'REVERT_CARD',
  ROLL_CARD: 'ROLL_CARD',
  CHANGE_FRONT_STAGE: 'CHANGE_FRONT_STAGE',
  CHANGE_BACK_STAGE: 'CHANGE_BACK_STAGE',
  SHUFFLE: 'SHUFFLE',
  SET_WORDS: 'SET_WORDS',
} as const;
